// Implement NftablesCompiler: Biên dịch FirewallPolicy thành script nftables cho table inet aegis_filter
// Đảm bảo không bao giờ sinh lệnh flush ruleset, tự động gắn counter và comment aegis:rule:<id>

use aegis_core::{AegisError, Result};
use aegis_models::firewall::{
    ConnectionState, FirewallAction, FirewallDirection, FirewallPolicy, FirewallRule,
    InterfaceSelector, PortSpec, TransportProtocol,
};
use aegis_policy::{PolicyHasher, PolicyValidator};
use chrono::Utc;

use super::{CompiledFirewallPolicy, FirewallCompiler};

/// Nftables Compiler chịu trách nhiệm sinh script nftables
pub struct NftablesCompiler;

impl NftablesCompiler {
    pub fn new() -> Self {
        Self
    }
}

impl Default for NftablesCompiler {
    fn default() -> Self {
        Self::new()
    }
}

impl FirewallCompiler for NftablesCompiler {
    fn compile(&self, policy: &FirewallPolicy) -> Result<CompiledFirewallPolicy> {
        // 1. Kiểm tra tính hợp lệ của Policy qua PolicyValidator
        let report = PolicyValidator::validate(policy);
        if !report.is_valid() {
            let error_msgs: Vec<String> = report.errors.iter().map(|e| e.message.clone()).collect();
            return Err(AegisError::Validation(format!(
                "Cannot compile invalid policy: {}",
                error_msgs.join("; ")
            )));
        }

        // 2. Tính SHA-256 Policy Hash
        let policy_hash = PolicyHasher::compute_hash(policy);
        let mut auto_generated_rules = Vec::new();

        let mut script = String::new();
        script.push_str("# Generated by AegisNode Firewall Compiler\n");
        script.push_str(&format!("# Policy Name: {}\n", policy.metadata.name));
        script.push_str(&format!("# Policy Hash: {}\n\n", policy_hash));

        // CHÚ Ý: Sử dụng 'destroy table' thay vì 'flush ruleset' để KHÔNG xoá tables của Docker/hệ thống
        script.push_str("destroy table inet aegis_filter\n\n");
        script.push_str("table inet aegis_filter {\n");

        // 3. Khai báo Chains (input, output, forward) với default policy
        let input_policy = match policy.defaults.input {
            FirewallAction::Accept => "accept",
            FirewallAction::Drop | FirewallAction::Reject => "drop",
        };
        let output_policy = match policy.defaults.output {
            FirewallAction::Accept => "accept",
            FirewallAction::Drop | FirewallAction::Reject => "drop",
        };
        let forward_policy = match policy.defaults.forward {
            FirewallAction::Accept => "accept",
            FirewallAction::Drop | FirewallAction::Reject => "drop",
        };

        // Chain Input
        script.push_str("    chain input {\n");
        script.push_str(&format!(
            "        type filter hook input priority filter; policy {input_policy};\n\n"
        ));

        // Auto-safety rule 1: Allow loopback nếu input policy là DROP
        if policy.defaults.input == FirewallAction::Drop {
            let has_loopback = policy.rules.iter().any(|r| {
                r.direction == FirewallDirection::Input
                    && r.action == FirewallAction::Accept
                    && r.interfaces.iter().any(|i| match i {
                        InterfaceSelector::Name(n) => n == "lo" || n == "loopback",
                        _ => false,
                    })
            });

            if !has_loopback {
                script.push_str(
                    "        iifname \"lo\" accept comment \"aegis:auto:allow-loopback\"\n",
                );
                auto_generated_rules.push("iifname \"lo\" accept".to_string());
            }
        }

        // Auto-safety rule 2: Allow established/related connections
        script.push_str("        ct state { established, related } accept comment \"aegis:auto:allow-established\"\n\n");
        auto_generated_rules.push("ct state { established, related } accept".to_string());

        // 4. Biên dịch user-defined input rules
        for rule in &policy.rules {
            if rule.direction == FirewallDirection::Input {
                script.push_str(&format!("        {}\n", Self::compile_rule(rule)));
            }
        }
        script.push_str("    }\n\n");

        // Chain Forward
        script.push_str("    chain forward {\n");
        script.push_str(&format!(
            "        type filter hook forward priority filter; policy {forward_policy};\n\n"
        ));
        script.push_str("        ct state { established, related } accept comment \"aegis:auto:allow-established\"\n\n");

        for rule in &policy.rules {
            if rule.direction == FirewallDirection::Forward {
                script.push_str(&format!("        {}\n", Self::compile_rule(rule)));
            }
        }
        script.push_str("    }\n\n");

        // Chain Output
        script.push_str("    chain output {\n");
        script.push_str(&format!(
            "        type filter hook output priority filter; policy {output_policy};\n\n"
        ));

        if policy.defaults.output == FirewallAction::Drop {
            let has_loopback = policy.rules.iter().any(|r| {
                r.direction == FirewallDirection::Output
                    && r.action == FirewallAction::Accept
                    && r.interfaces.iter().any(|i| match i {
                        InterfaceSelector::Name(n) => n == "lo" || n == "loopback",
                        _ => false,
                    })
            });

            if !has_loopback {
                script.push_str(
                    "        oifname \"lo\" accept comment \"aegis:auto:allow-loopback\"\n",
                );
            }
        }

        script.push_str("        ct state { established, related } accept comment \"aegis:auto:allow-established\"\n\n");

        for rule in &policy.rules {
            if rule.direction == FirewallDirection::Output {
                script.push_str(&format!("        {}\n", Self::compile_rule(rule)));
            }
        }
        script.push_str("    }\n");
        script.push_str("}\n");

        Ok(CompiledFirewallPolicy {
            nft_script: script,
            policy_hash,
            generated_at: Utc::now(),
            managed_tables: vec!["inet aegis_filter".to_string()],
            auto_generated_rules,
        })
    }
}

impl NftablesCompiler {
    /// Biên dịch 1 FirewallRule lẻ thành chuỗi nftables statement với counter & comment aegis:rule:<id>
    pub fn compile_rule(rule: &FirewallRule) -> String {
        let mut parts = Vec::new();

        // 1. Connection states filter
        if !rule.connection_states.is_empty() {
            let state_strs: Vec<&str> = rule
                .connection_states
                .iter()
                .map(|s| match s {
                    ConnectionState::New => "new",
                    ConnectionState::Established => "established",
                    ConnectionState::Related => "related",
                    ConnectionState::Invalid => "invalid",
                })
                .collect();
            parts.push(format!("ct state {{ {} }}", state_strs.join(", ")));
        }

        // 2. Transport Protocol & Destination Port filter
        if let Some(ref proto) = rule.protocol {
            match proto {
                TransportProtocol::Tcp => {
                    parts.push("tcp".to_string());
                    if !rule.destination_ports.is_empty() {
                        let port_strs: Vec<String> = rule
                            .destination_ports
                            .iter()
                            .map(Self::compile_port_spec)
                            .collect();
                        if port_strs.len() == 1 {
                            parts.push(format!("dport {}", port_strs[0]));
                        } else {
                            parts.push(format!("dport {{ {} }}", port_strs.join(", ")));
                        }
                    }
                }
                TransportProtocol::Udp => {
                    parts.push("udp".to_string());
                    if !rule.destination_ports.is_empty() {
                        let port_strs: Vec<String> = rule
                            .destination_ports
                            .iter()
                            .map(Self::compile_port_spec)
                            .collect();
                        if port_strs.len() == 1 {
                            parts.push(format!("dport {}", port_strs[0]));
                        } else {
                            parts.push(format!("dport {{ {} }}", port_strs.join(", ")));
                        }
                    }
                }
                TransportProtocol::Icmp => {
                    parts.push("icmp".to_string());
                }
                TransportProtocol::Icmpv6 => {
                    parts.push("icmpv6".to_string());
                }
            }
        }

        // 3. Source IP filter
        if !rule.source_cidrs.is_empty() {
            let cidr_strs: Vec<String> = rule.source_cidrs.iter().map(|c| c.0.clone()).collect();
            if cidr_strs.len() == 1 {
                parts.push(format!("ip saddr {}", cidr_strs[0]));
            } else {
                parts.push(format!("ip saddr {{ {} }}", cidr_strs.join(", ")));
            }
        }

        // 4. Destination IP filter
        if !rule.destination_cidrs.is_empty() {
            let cidr_strs: Vec<String> =
                rule.destination_cidrs.iter().map(|c| c.0.clone()).collect();
            if cidr_strs.len() == 1 {
                parts.push(format!("ip daddr {}", cidr_strs[0]));
            } else {
                parts.push(format!("ip daddr {{ {} }}", cidr_strs.join(", ")));
            }
        }

        // 5. Interface filter
        if !rule.interfaces.is_empty() {
            let iface_names: Vec<String> = rule
                .interfaces
                .iter()
                .map(|i| match i {
                    InterfaceSelector::Name(n) => format!("\"{n}\""),
                    InterfaceSelector::Role(r) => format!("\"{r:?}\"").to_lowercase(),
                })
                .collect();

            let iface_keyword = match rule.direction {
                FirewallDirection::Input => "iifname",
                FirewallDirection::Output => "oifname",
                FirewallDirection::Forward => "iifname",
            };

            if iface_names.len() == 1 {
                parts.push(format!("{iface_keyword} {}", iface_names[0]));
            } else {
                parts.push(format!("{iface_keyword} {{ {} }}", iface_names.join(", ")));
            }
        }

        // 6. Action & Counter statement
        parts.push("counter".to_string());

        let action_str = match rule.action {
            FirewallAction::Accept => "accept",
            FirewallAction::Drop => "drop",
            FirewallAction::Reject => "reject",
        };
        parts.push(action_str.to_string());

        // 7. Aegis rule ID comment tag
        let rule_id_str = rule.id.to_string();
        parts.push(format!("comment \"aegis:rule:{rule_id_str}\""));

        parts.join(" ")
    }

    /// Biên dịch PortSpec thành định dạng port nftables
    fn compile_port_spec(spec: &PortSpec) -> String {
        match spec {
            PortSpec::Single(p) => p.to_string(),
            PortSpec::Range(start, end) => format!("{start}-{end}"),
        }
    }
}
