// NAT Compiler: Biên dịch NatPolicy thành script nftables cho table ip aegis_nat
// Hỗ trợ Masquerade, SNAT, DNAT và Port Forwarding với counter & comment mã hóa

use aegis_core::Result;
use aegis_models::firewall::PortSpec;
use aegis_models::nat::NatPolicy;

/// NAT Compiler biên dịch NatPolicy sang script nftables
pub struct NatCompiler;

impl NatCompiler {
    pub fn new() -> Self {
        Self
    }

    /// Biên dịch NatPolicy thành chuỗi kịch bản nftables
    pub fn compile(&self, policy: &NatPolicy) -> Result<String> {
        let mut script = String::new();
        script.push_str("# Generated by AegisNode NAT Compiler\n");
        script.push_str(&format!("# NAT Policy Name: {}\n\n", policy.metadata.name));

        script.push_str("destroy table ip aegis_nat\n\n");
        script.push_str("table ip aegis_nat {\n");

        // Chain Prerouting (cho DNAT và Port Forwarding)
        script.push_str("    chain prerouting {\n");
        script.push_str("        type nat hook prerouting priority dstnat; policy accept;\n");

        for dnat in &policy.dnat_rules {
            let port_str = match &dnat.external_port {
                PortSpec::Single(p) => p.to_string(),
                PortSpec::Range(s, e) => format!("{s}-{e}"),
            };
            let dest_port = dnat
                .destination_port
                .map_or(String::new(), |p| format!(":{p}"));
            script.push_str(&format!(
                "        iifname \"{}\" ip protocol tcp dport {} counter dnat to {}{} comment \"aegis:nat:{}\"\n",
                dnat.in_interface, port_str, dnat.to_destination, dest_port, dnat.id
            ));
        }

        for pf in &policy.port_forward_rules {
            let port_str = match &pf.external_port {
                PortSpec::Single(p) => p.to_string(),
                PortSpec::Range(s, e) => format!("{s}-{e}"),
            };
            let src_cond = pf
                .source_cidr
                .as_ref()
                .map_or(String::new(), |c| format!("ip saddr {} ", c.0));
            script.push_str(&format!(
                "        iifname \"{}\" {}ip protocol tcp dport {} counter dnat to {}:{} comment \"aegis:nat:{}\"\n",
                pf.in_interface, src_cond, port_str, pf.destination_address, pf.destination_port, pf.id
            ));
        }
        script.push_str("    }\n\n");

        // Chain Postrouting (cho Masquerade và SNAT)
        script.push_str("    chain postrouting {\n");
        script.push_str("        type nat hook postrouting priority srcnat; policy accept;\n");

        for masq in &policy.masquerade_rules {
            let src_cond = masq
                .source_cidr
                .as_ref()
                .map_or(String::new(), |c| format!("ip saddr {} ", c.0));
            script.push_str(&format!(
                "        oifname \"{}\" {}counter masquerade comment \"aegis:nat:{}\"\n",
                masq.out_interface, src_cond, masq.id
            ));
        }

        for snat in &policy.snat_rules {
            let src_cond = snat
                .source_cidr
                .as_ref()
                .map_or(String::new(), |c| format!("ip saddr {} ", c.0));
            script.push_str(&format!(
                "        oifname \"{}\" {}counter snat to {} comment \"aegis:nat:{}\"\n",
                snat.out_interface, src_cond, snat.to_source, snat.id
            ));
        }
        script.push_str("    }\n");

        script.push_str("}\n");

        Ok(script)
    }
}

impl Default for NatCompiler {
    fn default() -> Self {
        Self::new()
    }
}
