// Implement NftablesCompiler: Biên dịch FirewallPolicy thành script nftables cho table inet aegis_filter
// Đảm bảo không bao giờ sinh lệnh flush ruleset, tự động gắn counter và comment aegis:rule:<id>

use aegis_core::{AegisError, Result};
use aegis_models::firewall::{
    ConnectionState, FirewallAction, FirewallDirection, FirewallPolicy, FirewallRule,
    InterfaceSelector, PortSpec, TransportProtocol,
};
use aegis_policy::{PolicyHasher, PolicyValidator};
use chrono::Utc;

use crate::compiler::{CompiledFirewallPolicy, FirewallCompiler};

/// Nftables Compiler chịu trách nhiệm sinh script nftables
pub struct NftablesCompiler;

impl NftablesCompiler {
    pub fn new() -> Self {
        Self
    }
}

impl Default for NftablesCompiler {
    fn default() -> Self {
        Self::new()
    }
}

impl FirewallCompiler for NftablesCompiler {
    fn compile(&self, policy: &FirewallPolicy) -> Result<CompiledFirewallPolicy> {
        // 1. Kiểm tra tính hợp lệ của Policy qua PolicyValidator
        let report = PolicyValidator::validate(policy);
        if !report.is_valid() {
            let error_msgs: Vec<String> = report.errors.iter().map(|e| e.message.clone()).collect();
            return Err(AegisError::Validation(format!(
                "Cannot compile invalid policy: {}",
                error_msgs.join("; ")
            )));
        }

        // 2. Tính SHA-256 Policy Hash
        let policy_hash = PolicyHasher::compute_hash(policy);
        let mut auto_generated_rules = Vec::new();

        let mut script = String::new();
        script.push_str("# Generated by AegisNode Firewall Compiler\n");
        script.push_str(&format!("# Policy Name: {}\n", policy.metadata.name));
        script.push_str(&format!("# Policy Hash: {}\n\n", policy_hash));

        // CHÚ Ý: Sử dụng 'destroy table' thay vì 'flush ruleset' để KHÔNG xoá tables của Docker/hệ thống
        script.push_str("destroy table inet aegis_filter\n\n");
        script.push_str("table inet aegis_filter {\n");

        // 3. Khai báo Chains (input, output, forward) với default policy
        let input_policy = match policy.defaults.input {
            FirewallAction::Accept => "accept",
            FirewallAction::Drop | FirewallAction::Reject => "drop",
        };
        let output_policy = match policy.defaults.output {
            FirewallAction::Accept => "accept",
            FirewallAction::Drop | FirewallAction::Reject => "drop",
        };
        let forward_policy = match policy.defaults.forward {
            FirewallAction::Accept => "accept",
            FirewallAction::Drop | FirewallAction::Reject => "drop",
        };

        // Chain Input
        script.push_str("    chain input {\n");
        script.push_str(&format!(
            "        type filter hook input priority filter; policy {input_policy};\n\n"
        ));

        // Auto-safety rule 1: Allow loopback nếu input policy là DROP
        if policy.defaults.input == FirewallAction::Drop {
            let has_loopback = policy.rules.iter().any(|r| {
                r.direction == FirewallDirection::Input
                    && r.action == FirewallAction::Accept
                    && r.interfaces.iter().any(|i| match i {
                        InterfaceSelector::Name(n) => n == "lo" || n == "loopback",
                        _ => false,
                    })
            });
            if !has_loopback {
                script.push_str("        iifname \"lo\" accept comment \"aegis:auto:loopback\"\n");
                auto_generated_rules.push("Auto-allow loopback interface (lo)".to_string());
            }

            // Auto-safety rule 2: Allow established/related nếu input policy là DROP
            let has_established = policy.rules.iter().any(|r| {
                r.direction == FirewallDirection::Input
                    && r.action == FirewallAction::Accept
                    && (r.connection_states.contains(&ConnectionState::Established)
                        || r.connection_states.contains(&ConnectionState::Related))
            });
            if !has_established {
                script.push_str("        ct state { established, related } accept comment \"aegis:auto:established\"\n");
                auto_generated_rules
                    .push("Auto-allow established/related connection state".to_string());
            }
        }

        // Auto-safety rule 3: Drop invalid state
        script.push_str("        ct state invalid drop comment \"aegis:auto:invalid\"\n");
        auto_generated_rules.push("Auto-drop invalid connection state".to_string());

        // Biên dịch các Rules hướng Input
        for rule in policy
            .rules
            .iter()
            .filter(|r| r.direction == FirewallDirection::Input)
        {
            let line = compile_rule_line(rule);
            script.push_str(&format!("        {line}\n"));
        }
        script.push_str("    }\n\n");

        // Chain Output
        script.push_str("    chain output {\n");
        script.push_str(&format!(
            "        type filter hook output priority filter; policy {output_policy};\n"
        ));
        for rule in policy
            .rules
            .iter()
            .filter(|r| r.direction == FirewallDirection::Output)
        {
            let line = compile_rule_line(rule);
            script.push_str(&format!("        {line}\n"));
        }
        script.push_str("    }\n\n");

        // Chain Forward
        script.push_str("    chain forward {\n");
        script.push_str(&format!(
            "        type filter hook forward priority filter; policy {forward_policy};\n"
        ));
        for rule in policy
            .rules
            .iter()
            .filter(|r| r.direction == FirewallDirection::Forward)
        {
            let line = compile_rule_line(rule);
            script.push_str(&format!("        {line}\n"));
        }
        script.push_str("    }\n");

        script.push_str("}\n");

        Ok(CompiledFirewallPolicy {
            nft_script: script,
            policy_hash,
            generated_at: Utc::now(),
            managed_tables: vec!["inet aegis_filter".to_string()],
            auto_generated_rules,
        })
    }
}

/// Chuyển đổi một FirewallRule struct sang dòng lệnh nftables rule chuẩn
fn compile_rule_line(rule: &FirewallRule) -> String {
    let mut parts = Vec::new();

    // 1. Interfaces
    for iface in &rule.interfaces {
        match iface {
            InterfaceSelector::Name(name) => {
                if rule.direction == FirewallDirection::Output {
                    parts.push(format!("oifname \"{name}\""));
                } else {
                    parts.push(format!("iifname \"{name}\""));
                }
            }
            InterfaceSelector::Role(_) => {
                // InterfaceRole sẽ được map theo node inventory ở runtime; tạm thời dùng comment
            }
        }
    }

    // 2. Connection States
    if !rule.connection_states.is_empty() {
        let states: Vec<&str> = rule
            .connection_states
            .iter()
            .map(|s| match s {
                ConnectionState::New => "new",
                ConnectionState::Established => "established",
                ConnectionState::Related => "related",
                ConnectionState::Invalid => "invalid",
            })
            .collect();
        if states.len() == 1 {
            parts.push(format!("ct state {}", states[0]));
        } else {
            parts.push(format!("ct state {{ {} }}", states.join(", ")));
        }
    }

    // 3. Protocol
    if let Some(proto) = rule.protocol {
        match proto {
            TransportProtocol::Tcp => parts.push("ip protocol tcp".to_string()),
            TransportProtocol::Udp => parts.push("ip protocol udp".to_string()),
            TransportProtocol::Icmp => parts.push("ip protocol icmp".to_string()),
            TransportProtocol::Icmpv6 => parts.push("ip6 nexthdr icmpv6".to_string()),
        }
    }

    // 4. Source CIDRs (Dùng nftables set nếu có nhiều CIDR)
    if !rule.source_cidrs.is_empty() {
        if rule.source_cidrs.len() == 1 {
            parts.push(format!("ip saddr {}", rule.source_cidrs[0].0));
        } else {
            let cidrs: Vec<String> = rule.source_cidrs.iter().map(|c| c.0.clone()).collect();
            parts.push(format!("ip saddr {{ {} }}", cidrs.join(", ")));
        }
    }

    // 5. Destination CIDRs
    if !rule.destination_cidrs.is_empty() {
        if rule.destination_cidrs.len() == 1 {
            parts.push(format!("ip daddr {}", rule.destination_cidrs[0].0));
        } else {
            let cidrs: Vec<String> = rule.destination_cidrs.iter().map(|c| c.0.clone()).collect();
            parts.push(format!("ip daddr {{ {} }}", cidrs.join(", ")));
        }
    }

    // 6. Destination Ports
    if !rule.destination_ports.is_empty() {
        let port_strs: Vec<String> = rule
            .destination_ports
            .iter()
            .map(|p| match p {
                PortSpec::Single(port) => port.to_string(),
                PortSpec::Range(start, end) => format!("{start}-{end}"),
            })
            .collect();

        if port_strs.len() == 1 {
            parts.push(format!("tcp dport {}", port_strs[0]));
        } else {
            parts.push(format!("tcp dport {{ {} }}", port_strs.join(", ")));
        }
    }

    // 7. Rate limit
    if let Some(rate_limit) = &rule.rate_limit {
        parts.push(format!(
            "limit rate {}/second burst {} packets",
            rate_limit.packets_per_second, rate_limit.burst
        ));
    }

    // 8. Log options
    if let Some(log) = &rule.log_options {
        if log.enabled {
            let prefix = if log.prefix.is_empty() {
                format!("aegis:{}: ", rule.id)
            } else {
                log.prefix.clone()
            };
            parts.push(format!("log prefix \"{prefix}\""));
        }
    }

    // 9. Mandatory Counter
    parts.push("counter".to_string());

    // 10. Action (accept / drop / reject)
    let action_str = match rule.action {
        FirewallAction::Accept => "accept",
        FirewallAction::Drop => "drop",
        FirewallAction::Reject => "reject",
    };
    parts.push(action_str.to_string());

    // 11. Mandatory Comment "aegis:rule:<rule-id>"
    parts.push(format!("comment \"aegis:rule:{}\"", rule.id));

    parts.join(" ")
}
